version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: payment-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  app:
    build: .
    container_name: payment-app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
volumes:
  redis-data: 